### ISSUE TITLE
Updates to agentmon require a recompile of the application

### ISSUE THREAD

**Issue by freeformz** [heroku/heroku-buildpack-metrics#2]
One way to solve this is to download the agent on dyno boot instead.
This closes the window to upgrade to 24h max due to dyno cycling behavior. 
But does leave us to the mercy of future changes in that cycling behavior.
And there is no real way to roll out a change immediately (security issue maybe?), should that be necessary (beyond scripting up finding all apps with the feature flag and restarting all of their dynos).

Another option is to have agentmon be self updating, where it polls a know location for some meta-data about the current version and compares it to it's version, then downloads and update and exists (or execs the update).

Other thoughts?

**Comment by apg** [comment]
this is now ready for review again.
